param(
    [string]$DbPassword,
    [string]$DbUsername,
    [string]$DbUrl,
    [int]$Port = 8080,
    [switch]$SkipRun
)

$ErrorActionPreference = "Stop"

function Test-Blank {
    param([string]$Value)
    return [string]::IsNullOrWhiteSpace($Value)
}

function New-LocalSecret {
    $bytes = New-Object byte[] 48
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($bytes)
    }
    finally {
        $rng.Dispose()
    }

    return [Convert]::ToBase64String($bytes).TrimEnd("=").Replace("+", "-").Replace("/", "_")
}

function Read-LocalSecrets {
    param([string]$Path)

    $values = @{}
    if (-not (Test-Path -LiteralPath $Path)) {
        return $values
    }

    Get-Content -LiteralPath $Path | ForEach-Object {
        $line = $_.Trim()
        if ($line.Length -eq 0 -or $line.StartsWith("#")) {
            return
        }

        $index = $line.IndexOf("=")
        if ($index -le 0) {
            return
        }

        $key = $line.Substring(0, $index).Trim()
        $value = $line.Substring($index + 1).Trim()
        $values[$key] = $value
    }

    return $values
}

function Write-LocalSecrets {
    param(
        [string]$Path,
        [hashtable]$Secrets
    )

    $lines = @(
        "# Generated by start-local.ps1. Do not commit this file.",
        "SMART_LAB_JWT_SECRET=$($Secrets["SMART_LAB_JWT_SECRET"])",
        "ACADEMIC_CREDENTIAL_SECRET=$($Secrets["ACADEMIC_CREDENTIAL_SECRET"])"
    )

    Set-Content -LiteralPath $Path -Value $lines -Encoding UTF8
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location -LiteralPath $scriptDir

$secretPath = Join-Path $scriptDir ".local-dev-secrets.properties"
$secrets = Read-LocalSecrets -Path $secretPath
$changed = $false

if (-not $secrets.ContainsKey("SMART_LAB_JWT_SECRET") -or (Test-Blank $secrets["SMART_LAB_JWT_SECRET"])) {
    $secrets["SMART_LAB_JWT_SECRET"] = New-LocalSecret
    $changed = $true
}

if (-not $secrets.ContainsKey("ACADEMIC_CREDENTIAL_SECRET") -or (Test-Blank $secrets["ACADEMIC_CREDENTIAL_SECRET"])) {
    $secrets["ACADEMIC_CREDENTIAL_SECRET"] = New-LocalSecret
    $changed = $true
}

if ($changed) {
    Write-LocalSecrets -Path $secretPath -Secrets $secrets
}

if (Test-Blank $env:SMART_LAB_JWT_SECRET) {
    $env:SMART_LAB_JWT_SECRET = $secrets["SMART_LAB_JWT_SECRET"]
}

if (Test-Blank $env:ACADEMIC_CREDENTIAL_SECRET) {
    $env:ACADEMIC_CREDENTIAL_SECRET = $secrets["ACADEMIC_CREDENTIAL_SECRET"]
}

if (Test-Blank $DbUsername) {
    $DbUsername = if (Test-Blank $env:SMART_LAB_DB_USERNAME) { "root" } else { $env:SMART_LAB_DB_USERNAME }
}

if (Test-Blank $DbUrl) {
    $DbUrl = if (Test-Blank $env:SMART_LAB_DB_URL) { "jdbc:mysql://localhost:3306/smart_lab_basic" } else { $env:SMART_LAB_DB_URL }
}

if (-not (Test-Blank $DbPassword)) {
    $env:SMART_LAB_DB_PASSWORD = $DbPassword
}

$env:SMART_LAB_DB_USERNAME = $DbUsername
$env:SMART_LAB_DB_URL = $DbUrl

Write-Host "Local secrets loaded from $secretPath"
Write-Host "Database URL: $env:SMART_LAB_DB_URL"
Write-Host "Database user: $env:SMART_LAB_DB_USERNAME"
if (Test-Blank $env:SMART_LAB_DB_PASSWORD) {
    Write-Host "Database password: empty"
}
else {
    Write-Host "Database password: configured"
}

if ($SkipRun) {
    return
}

& mvn.cmd "-Dspring-boot.run.arguments=--server.port=$Port" spring-boot:run
